GUIDE_BASE=guide

GUIDE_PARTS= \
metadata.tex \
guide/guide.tex \
guide/content.tex \
guide/titlepage.tex \
guide/license.tex \
guide/foreword.tex \
guide/ack.tex \
bib/*.bib \
exercises/*.tex

GUIDE_OUT=guide-lambdas

GUIDE_PDF=$(GUIDE_OUT).pdf

GUIDE_FINAL_PDF=$(FINAL_DIR)/$(GUIDE_PDF)
